#!/bin/sh
set -x

switch=br0

if [ -n "$1" ];then
        # tunctl -u `whoami` -t $1 (use ip tuntap instead!)
        ip tuntap add $1 mode tap user `whoami`
        ip link set $1 up
        sleep 0.5s
        ip link set $1 master $switch
        # brctl addif $switch $1 (use ip link instead!)
        sudo ip link set $1 txqueuelen 10000
        exit 0
else
        echo "Error: no interface specified"
        exit 1
fi